export const browserCoreExamples = [
  "dainel browser status",
  "dainel browser start",
  "dainel browser stop",
  "dainel browser tabs",
  "dainel browser open https://example.com",
  "dainel browser focus abcd1234",
  "dainel browser close abcd1234",
  "dainel browser screenshot",
  "dainel browser screenshot --full-page",
  "dainel browser screenshot --ref 12",
  "dainel browser snapshot",
  "dainel browser snapshot --format aria --limit 200",
  "dainel browser snapshot --efficient",
  "dainel browser snapshot --labels",
];

export const browserActionExamples = [
  "dainel browser navigate https://example.com",
  "dainel browser resize 1280 720",
  "dainel browser click 12 --double",
  'dainel browser type 23 "hello" --submit',
  "dainel browser press Enter",
  "dainel browser hover 44",
  "dainel browser drag 10 11",
  "dainel browser select 9 OptionA OptionB",
  "dainel browser upload /tmp/file.pdf",
  'dainel browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "dainel browser dialog --accept",
  'dainel browser wait --text "Done"',
  "dainel browser evaluate --fn '(el) => el.textContent' --ref 7",
  "dainel browser console --level error",
  "dainel browser pdf",
];
